# -*- coding: utf-8 -*-
"""assignment_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nWLQy3jtin7Dub35SgpnOOLZXeZT-gS
"""

# Storing patient details
patient_name = "Muthu Kumar "
patient_age = 35
patient_weight_kg = 75
patient_height_m = 1.75

# Calculating BMI
patient_bmi = patient_weight_kg / (patient_height_m ** 2)

# Displaying patient details
print(f"Patient Name: {patient_name}")
print(f"Age: {patient_age} years")
print(f"BMI: {patient_bmi:.2f}")

# Function to determine BMI category
def determine_bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal weight"
    elif 25 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Obese"

# Patient details
patient_name = "John Doe"
patient_age = 45
patient_bmi = 28.5

# Determine BMI category
bmi_category = determine_bmi_category(patient_bmi)

# Print the patient details along with BMI category
print(f"Patient Name: {patient_name}")
print(f"Patient Age: {patient_age}")
print(f"Patient BMI: {patient_bmi}")
print(f"BMI Category: {bmi_category}")

import numpy as np

# Store a week's heart rate readings in a NumPy array (e.g., 7 readings, one for each day)
heart_rate_readings = np.array([72, 75, 68, 70, 74, 78, 69])

# Calculate the average, highest, and lowest heart rate
average_heart_rate = np.mean(heart_rate_readings)
highest_heart_rate = np.max(heart_rate_readings)
lowest_heart_rate = np.min(heart_rate_readings)

# Print the results
print("Average Heart Rate:", average_heart_rate)
print("Highest Heart Rate:", highest_heart_rate)
print("Lowest Heart Rate:", lowest_heart_rate)

import pandas as pd

# Creating the DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [45, 50, 38, 60, 55],
    "Cholesterol": [200, 220, 180, 250, 230]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

# Sample patient data: (Name, Weight in kg, Height in meters)
patients = [
    ("Alice", 68, 1.65),
    ("Bob", 85, 1.75),
    ("Charlie", 95, 1.80),
    ("David", 76, 1.70)
]

# Function to calculate BMI
def calculate_bmi(weight, height):
    return weight / (height ** 2)

# Add BMI to patient data
patients_with_bmi = [(name, weight, height, calculate_bmi(weight, height)) for name, weight, height in patients]

# Sort patients by BMI in descending order
sorted_patients = sorted(patients_with_bmi, key=lambda x: x[3], reverse=True)

# Print results
print("Patients sorted by BMI (highest to lowest):")
for patient in sorted_patients:
    print(f"{patient[0]} - BMI: {patient[3]:.2f}")

import pandas as pd

# Example DataFrame
data = {'Patient_ID': [1, 2, 3, 4, 5],
        'BMI': [22, 27, 31, 24, 29],
        'Cholesterol': [180, 220, 250, 190, 240]}

df = pd.DataFrame(data)

# Function to classify risk
def classify_risk(row):
    if row['BMI'] >= 30 or row['Cholesterol'] >= 240:
        return "High"
    elif row['BMI'] >= 25 or row['Cholesterol'] >= 200:
        return "Medium"
    else:
        return "Low"

# Apply classification
df['Risk_Level'] = df.apply(classify_risk, axis=1)

print(df)

import pandas as pd

# Sample patient data
data = {
    'Patient_ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Cholesterol': [180, 220, 190, 250, 210]
}

# Create DataFrame
df = pd.DataFrame(data)

# Set cholesterol threshold
threshold = 200

# Filter patients above the threshold
high_cholesterol_patients = df[df['Cholesterol'] > threshold]

# Display results
print(high_cholesterol_patients)