# -*- coding: utf-8 -*-
"""Session_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NRBRpAqQseZWOSsTdzL2e28ttkXT6GD
"""

customer_name = "John Doe"
customer_age = 28
customer_balance = 120.75
print("Customer:", customer_name)
print("Age:", customer_age)
print("Balance:", customer_balance)

product_price = 200
discount = product_price * 0.10  # 10% discount
final_price = product_price - discount
print("Final Price after Discount:", final_price)

import numpy as np
sales = np.array([150, 200, 250, 300, 400, 350, 500])
print("Sales Data:", sales)

print("Average Sales:", np.mean(sales))
print("Highest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))



import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie"],
"Age": [25, 30, 35],
"Amount Spent": [120, 200, 150]
          }
df = pd.DataFrame(data)
print(df)

import pandas as pd
from google.colab import files

uploaded = files.upload()  # Upload your CSV file

# Try reading the CSV with 'latin-1' encoding
df = pd.read_csv("s_j.csv", encoding='ISO-8859-1')  # Replace with your file name

# Or try 'ISO-8859-1', another common encoding for Western European languages
# df = pd.read_csv("customer_data.csv", encoding='ISO-8859-1')

print(df.head())

high_spenders = df[df["disp"] > 100]
print(high_spenders)

high_spenders = df[df[""] > 150]
print(high_spenders)



# Rename the column containing the Amount Spent.
 df = df.rename(columns={'Existing_column_name': 'Amount Spent'})  # Replace 'Existing_column_name'

 high_spenders = df[df["Amount Spent"] > 150]
 print(high_spenders)

df_sorted = df.sort_values(by="disp", ascending=False)
print(df_sorted)

df["cyl"] = df["disp"] // 10
print(df)

df.to_csv("cleaned_customer_data.csv", index=False)
files.download("cleaned_customer_data.csv")  # Download the file